import { useState } from 'react';
import { supabase, useCloud, syncLibrary, guestLibrary } from '../lib/cloud';
import { useCourse } from '../lib/courseStore';
import { getOriginal } from '../lib/originals';
import { mergeAttempts } from '../lib/cloudMerge';
import type { Course } from '../lib/course';

export function CloudAccount() {
 const cloud=useCloud();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function auth(action:'login'|'signup'|'reset'){
  if(!supabase)return;setBusy(true);setMessage('');
  try {const result=action==='reset'?await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin}):action==='signup'?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;setPassword('');setMessage(action==='login'?'Sesión iniciada.':action==='signup'?'Revisa tu correo para confirmar la cuenta. Después vuelve e inicia sesión.':'Revisa tu correo para recuperar el acceso.');}
  catch(e){setMessage(e instanceof Error?e.message:'No se pudo acceder.');}finally{setBusy(false);}
 }
 const recovery=cloud.recovery;const setRecovery=(recovery:boolean)=>useCloud.setState({recovery});
 async function resetPassword(){if(!supabase)return;setBusy(true);const {error}=await supabase.auth.updateUser({password});setMessage(error?.message||'Contraseña actualizada.');if(!error){setRecovery(false);setPassword('');}setBusy(false);}
 if(!supabase)return <p>Modo local. La conexión con tu cuenta aún no está configurada.</p>;
 return <section className="panel space-y-3"><h2 className="text-lg font-bold">Mi cuenta</h2>{recovery?<><label>Nueva contraseña<input type="password" autoComplete="new-password" className="border rounded p-2 block" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="action" disabled={busy||password.length<8} onClick={resetPassword}>Guardar nueva contraseña</button></>:cloud.userId?<><p>{cloud.email}</p><div className="flex gap-3 flex-wrap"><button className="action" disabled={cloud.busy} onClick={()=>void syncLibrary()}>{cloud.busy?'Sincronizando…':'Sincronizar lecciones y avances'}</button><button className="underline" disabled={cloud.busy} onClick={async()=>{const {error}=await supabase!.auth.signOut();if(error)setMessage(error.message);}}>Cerrar sesión</button></div><p className="text-sm">Pulsa Sincronizar al terminar de estudiar y al abrir otro dispositivo. Los cambios sin sincronizar permanecen en este navegador.</p></>:<details><summary className="cursor-pointer">Iniciar sesión / Crear mi cuenta</summary><p className="my-3">Usa la misma cuenta en tu computadora y celular. Puedes seguir estudiando sin iniciar sesión.</p><form className="space-y-3" onSubmit={e=>{e.preventDefault();void auth('login');}}><label className="block">Correo<input type="email" autoComplete="email" className="border rounded p-2 block w-full" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="block">Contraseña<input type="password" autoComplete="current-password" className="border rounded p-2 block w-full" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label><button className="action" disabled={busy}>Entrar</button><button type="button" className="underline ml-3" disabled={busy||!email||password.length<8} onClick={()=>void auth('signup')}>Crear cuenta</button><button type="button" className="underline block" disabled={busy||!email} onClick={()=>void auth('reset')}>Olvidé mi contraseña</button></form></details>}{message&&<p role="status">{message}</p>}{cloud.status&&<p role="status">{cloud.status}</p>}</section>;
}
export default function MyLessons({onStudy,onImport}:{onStudy:()=>void;onImport:()=>void}) {
 const courses=useCourse(s=>s.courses);const cloud=useCloud();const [message,setMessage]=useState('');
 async function original(c:Course){
  try{let href='';if(c.originalPath&&supabase&&cloud.userId){const {data,error}=await supabase.storage.from('english-originals').createSignedUrl(c.originalPath,60);if(error)throw error;href=data.signedUrl;}
   else{const blob=await getOriginal(c.id);if(!blob)throw new Error('Este material antiguo no conserva el archivo original. Vuelve a subirlo desde Importar / contenido.');href=URL.createObjectURL(blob);setTimeout(()=>URL.revokeObjectURL(href),60000);}
   const link=document.createElement('a');link.href=href;link.download=c.originalName||c.fileName;link.target='_blank';link.rel='noopener';link.click();
  }catch(e){setMessage(e instanceof Error?e.message:'No se pudo abrir el archivo.');}
 }
 async function migrate(){try{const guest=guestLibrary();const s=useCourse.getState();for(const c of guest.courses||[])if(!s.courses.some(x=>x.id===c.id))useCourse.getState().saveCourse(c);useCourse.setState({attempts:mergeAttempts(useCourse.getState().attempts,guest.attempts||{})});await syncLibrary();}catch{setMessage('No se pudieron copiar las lecciones locales. Los originales siguen en el navegador.');}}
 return <section className="space-y-4"><h1 className="text-2xl font-bold">Mis lecciones</h1><button className="action" onClick={onImport}>Agregar PDF o fotos</button><p>{cloud.userId?'Tu biblioteca privada. Guarda y pulsa Sincronizar para verla desde otro dispositivo.':'Biblioteca de este navegador. Inicia sesión para guardar una copia en tu cuenta.'}</p>{cloud.userId&&<details><summary>Recuperar lecciones anteriores de este navegador</summary><p>Copiará el texto y los avances locales a esta cuenta. Los archivos antiguos que nunca se guardaron deberán subirse de nuevo.</p><button className="underline" disabled={cloud.busy} onClick={()=>void migrate()}>Copiar mis lecciones locales a esta cuenta</button></details>}{!courses.length&&<p>Todavía no tienes lecciones guardadas. Puedes agregar archivos o practicar las lecciones básicas.</p>}{courses.map(c=><article className="panel space-y-3" key={c.id}><label className="block">Nombre de la lección<input className="border rounded p-2 w-full" defaultValue={c.fileName} key={`${c.id}-${c.fileName}`} onBlur={e=>{const name=e.target.value.trim();if(name&&name!==c.fileName)useCourse.getState().saveCourse({...c,fileName:name});}}/></label><p>{c.pages.length} páginas · {c.cards.length} ejercicios</p><p className="text-sm">{c.originalPath?'Original guardado en tu cuenta':c.originalName?'Original guardado en este navegador':'Sin archivo original (lección básica o importación anterior)'}</p><button className="action" onClick={()=>{useCourse.getState().selectCourse(c.id);onStudy();}}>Estudiar</button>{(c.originalName||c.originalPath)&&<button className="underline ml-3" onClick={()=>void original(c)}>Abrir original</button>}<details><summary>Ver contenido</summary>{c.pages.map((p,i)=><div key={i}><h3>Página {p.page}</h3><p className="whitespace-pre-wrap">{p.text}</p></div>)}</details></article>)}{message&&<p role="alert">{message}</p>}</section>;
}
